services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: krushovice
      POSTGRES_PASSWORD: 9874123Kr
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
       - "5050:80"